### ISSUE TITLE
[BUG] 영상 등록시 500 에러 발생

### ISSUE THREAD

**Issue by seongho-joo** [numbble/backend#37]
### :no_good: 버그 내용
* 영상을 등록할 시, `Internal Server Error` 500 에러 발생한다.

### :point_right: 재현 방법
* 포스트맨에서 post `/v1/videos` api 요청 시, `Internal Server Error` 가 발생한다.

### :eyes: 예상 응답
```json
{
    "data" : {
        "id": 1,
        "title": "title",
        "videoUrl": "https://d659rm6fgd091.cloudfront.net/video/1",
        "thumbnailUrl": "https://d659rm6fgd091.cloudfront.net/video/thumbnail/1",
        "price": 199999,
        "viewCount": 0,
        "likeCount": 0,
        "member": { "name": "성호" },
        "category": { "id": 5, "name": "기타" },
        "usedStatus": false,
        "description": "a"
    },
	"message" : "영상 업로드 성공"
}
```

### :camera: 화면 캡쳐
- 요청 값
<img width="1190" alt="스크린샷 2022-05-12 오후 8 19 27" src="https://user-images.githubusercontent.com/45463495/168063830-46c3d7fa-1579-472b-af16-4e81a529b1f7.png">

-  에러 로그
<img width="1286" alt="스크린샷 2022-05-12 오후 8 22 29" src="https://user-images.githubusercontent.com/45463495/168063847-6b56b25b-bd87-4505-a390-87e311666672.png">

### :bulb: 부가 설명
* 해당 문제에 대하여 부가적인 설명이 있다면 설명해주세요.

**Comment by jaeesu** [comment]
api 요청값 포스트맨 화면과 에러 로그 캡쳐해주세요~

**Comment by seongho-joo** [comment]
트랜잭션 스코프의 벗어난 곳에서 영속성 엔티티를 조회를 하는 것이 원인이었습니다. 이를 해결하기 위해 연관관계 편의 메서드를 제거했더니 정상적으로 작동되었습니다!
